// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// E_num_DeepState_TestHarness_generation.cpp and E_num_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <ctime>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

int E_num(NumericVector& rides);

TEST(,){
  RInside R;
  std::time_t t = std::time(0);
  std::cout << "input starts" << std::endl;
  NumericVector rides  = RcppDeepState_NumericVector();
  std::string rides_t = "/home/akhila/fuzzer_packages/fuzzedpackages/eddington/inst/testfiles/E_num/AFL_E_num/afl_inputs/" + std::to_string(t) + "_rides.qs";
  qs::c_qsave(rides,rides_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "rides values: "<< rides << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    E_num(rides);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
