// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// cpp_find_local_cases_DeepState_TestHarness_generation.cpp and cpp_find_local_cases_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <ctime>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

Rcpp::IntegerVector cpp_find_local_cases(Rcpp::IntegerVector alpha, Rcpp::IntegerVector cluster, int i);

TEST(,){
  RInside R;
  std::time_t t = std::time(0);
  std::cout << "input starts" << std::endl;
  IntegerVector alpha  = RcppDeepState_IntegerVector();
  std::string alpha_t = "/home/akhila/fuzzer_packages/fuzzedpackages/o2geosocial/inst/testfiles/cpp_find_local_cases/AFL_cpp_find_local_cases/afl_inputs/" + std::to_string(t) + "_alpha.qs";
  qs::c_qsave(alpha,alpha_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "alpha values: "<< alpha << std::endl;
  IntegerVector cluster  = RcppDeepState_IntegerVector();
  std::string cluster_t = "/home/akhila/fuzzer_packages/fuzzedpackages/o2geosocial/inst/testfiles/cpp_find_local_cases/AFL_cpp_find_local_cases/afl_inputs/" + std::to_string(t) + "_cluster.qs";
  qs::c_qsave(cluster,cluster_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "cluster values: "<< cluster << std::endl;
  IntegerVector i(1);
  i[0]  = RcppDeepState_int();
  std::string i_t = "/home/akhila/fuzzer_packages/fuzzedpackages/o2geosocial/inst/testfiles/cpp_find_local_cases/AFL_cpp_find_local_cases/afl_inputs/" + std::to_string(t) + "_i.qs";
  qs::c_qsave(i,i_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "i values: "<< i << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    cpp_find_local_cases(alpha,cluster,i[0]);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
