// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// phd_init_DeepState_TestHarness_generation.cpp and phd_init_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

double phd_init(const arma::mat& B, const arma::mat& X, const arma::mat& Y, double bw, int ncore);

TEST(,){
  static int rinside_flag = 0;
  if(rinside_flag == 0)
  {
    rinside_flag = 1;
    RInside R;
  } std::time_t current_timestamp = std::time(0);
  std::cout << "input starts" << std::endl;
  std::ofstream B_stream;
  arma::mat B  = RcppDeepState_mat();
  B_stream.open("/home/akhila/fuzzer_packages/fuzzedpackages/orthoDr/inst/testfiles/phd_init/inputs/B");
  B_stream << B;
  std::cout << "B values: "<< B << std::endl;
  B_stream.close();
  std::ofstream X_stream;
  arma::mat X  = RcppDeepState_mat();
  X_stream.open("/home/akhila/fuzzer_packages/fuzzedpackages/orthoDr/inst/testfiles/phd_init/inputs/X");
  X_stream << X;
  std::cout << "X values: "<< X << std::endl;
  X_stream.close();
  std::ofstream Y_stream;
  arma::mat Y  = RcppDeepState_mat();
  Y_stream.open("/home/akhila/fuzzer_packages/fuzzedpackages/orthoDr/inst/testfiles/phd_init/inputs/Y");
  Y_stream << Y;
  std::cout << "Y values: "<< Y << std::endl;
  Y_stream.close();
  NumericVector bw(1);
  bw[0]  = RcppDeepState_double();
  std::string bw_t = "/home/akhila/fuzzer_packages/fuzzedpackages/orthoDr/inst/testfiles/phd_init/libFuzzer_phd_init/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_bw.qs";
  qs::c_qsave(bw,bw_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "bw values: "<< bw << std::endl;
  IntegerVector ncore(1);
  ncore[0]  = RcppDeepState_int();
  std::string ncore_t = "/home/akhila/fuzzer_packages/fuzzedpackages/orthoDr/inst/testfiles/phd_init/libFuzzer_phd_init/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_ncore.qs";
  qs::c_qsave(ncore,ncore_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "ncore values: "<< ncore << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    phd_init(B,X,Y,bw[0],ncore[0]);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
