// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// LBSPRopt_DeepState_TestHarness_generation.cpp and LBSPRopt_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

double LBSPRopt(NumericVector pars, NumericVector CAL, int nage, int nlen, double CVLinf, NumericVector LenBins, NumericVector LenMids, double MK, double Linf, NumericVector rLens, NumericMatrix Prob, NumericVector Ml, double L50, double L95, double Beta);

TEST(,){
  RInside R;
  std::cout << "input starts" << std::endl;
  NumericVector pars  = RcppDeepState_NumericVector();
  qs::c_qsave(pars,"/home/akhila/fuzzer_packages/fuzzedpackages/DLMtool/inst/testfiles/LBSPRopt/inputs/pars.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "pars values: "<< pars << std::endl;
  NumericVector CAL  = RcppDeepState_NumericVector();
  qs::c_qsave(CAL,"/home/akhila/fuzzer_packages/fuzzedpackages/DLMtool/inst/testfiles/LBSPRopt/inputs/CAL.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "CAL values: "<< CAL << std::endl;
  IntegerVector nage(1);
  nage[0]  = RcppDeepState_int();
  qs::c_qsave(nage,"/home/akhila/fuzzer_packages/fuzzedpackages/DLMtool/inst/testfiles/LBSPRopt/inputs/nage.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "nage values: "<< nage << std::endl;
  IntegerVector nlen(1);
  nlen[0]  = RcppDeepState_int();
  qs::c_qsave(nlen,"/home/akhila/fuzzer_packages/fuzzedpackages/DLMtool/inst/testfiles/LBSPRopt/inputs/nlen.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "nlen values: "<< nlen << std::endl;
  NumericVector CVLinf(1);
  CVLinf[0]  = RcppDeepState_double();
  qs::c_qsave(CVLinf,"/home/akhila/fuzzer_packages/fuzzedpackages/DLMtool/inst/testfiles/LBSPRopt/inputs/CVLinf.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "CVLinf values: "<< CVLinf << std::endl;
  NumericVector LenBins  = RcppDeepState_NumericVector();
  qs::c_qsave(LenBins,"/home/akhila/fuzzer_packages/fuzzedpackages/DLMtool/inst/testfiles/LBSPRopt/inputs/LenBins.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "LenBins values: "<< LenBins << std::endl;
  NumericVector LenMids  = RcppDeepState_NumericVector();
  qs::c_qsave(LenMids,"/home/akhila/fuzzer_packages/fuzzedpackages/DLMtool/inst/testfiles/LBSPRopt/inputs/LenMids.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "LenMids values: "<< LenMids << std::endl;
  NumericVector MK(1);
  MK[0]  = RcppDeepState_double();
  qs::c_qsave(MK,"/home/akhila/fuzzer_packages/fuzzedpackages/DLMtool/inst/testfiles/LBSPRopt/inputs/MK.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "MK values: "<< MK << std::endl;
  NumericVector Linf(1);
  Linf[0]  = RcppDeepState_double();
  qs::c_qsave(Linf,"/home/akhila/fuzzer_packages/fuzzedpackages/DLMtool/inst/testfiles/LBSPRopt/inputs/Linf.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "Linf values: "<< Linf << std::endl;
  NumericVector rLens  = RcppDeepState_NumericVector();
  qs::c_qsave(rLens,"/home/akhila/fuzzer_packages/fuzzedpackages/DLMtool/inst/testfiles/LBSPRopt/inputs/rLens.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "rLens values: "<< rLens << std::endl;
  NumericMatrix Prob  = RcppDeepState_NumericMatrix();
  qs::c_qsave(Prob,"/home/akhila/fuzzer_packages/fuzzedpackages/DLMtool/inst/testfiles/LBSPRopt/inputs/Prob.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "Prob values: "<< Prob << std::endl;
  NumericVector Ml  = RcppDeepState_NumericVector();
  qs::c_qsave(Ml,"/home/akhila/fuzzer_packages/fuzzedpackages/DLMtool/inst/testfiles/LBSPRopt/inputs/Ml.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "Ml values: "<< Ml << std::endl;
  NumericVector L50(1);
  L50[0]  = RcppDeepState_double();
  qs::c_qsave(L50,"/home/akhila/fuzzer_packages/fuzzedpackages/DLMtool/inst/testfiles/LBSPRopt/inputs/L50.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "L50 values: "<< L50 << std::endl;
  NumericVector L95(1);
  L95[0]  = RcppDeepState_double();
  qs::c_qsave(L95,"/home/akhila/fuzzer_packages/fuzzedpackages/DLMtool/inst/testfiles/LBSPRopt/inputs/L95.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "L95 values: "<< L95 << std::endl;
  NumericVector Beta(1);
  Beta[0]  = RcppDeepState_double();
  qs::c_qsave(Beta,"/home/akhila/fuzzer_packages/fuzzedpackages/DLMtool/inst/testfiles/LBSPRopt/inputs/Beta.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "Beta values: "<< Beta << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    LBSPRopt(pars,CAL,nage[0],nlen[0],CVLinf[0],LenBins,LenMids,MK[0],Linf[0],rLens,Prob,Ml,L50[0],L95[0],Beta[0]);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
