// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// costTotCPP_DeepState_TestHarness_generation.cpp and costTotCPP_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

Rcpp::NumericVector costTotCPP(const Rcpp::NumericMatrix& flow, const Rcpp::NumericMatrix& cost);

TEST(,){
  RInside R;
  std::cout << "input starts" << std::endl;
  NumericMatrix flow  = RcppDeepState_NumericMatrix();
  qs::c_qsave(flow,"/home/akhila/fuzzer_packages/fuzzedpackages/epiphy/inst/testfiles/costTotCPP/inputs/flow.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "flow values: "<< flow << std::endl;
  NumericMatrix cost  = RcppDeepState_NumericMatrix();
  qs::c_qsave(cost,"/home/akhila/fuzzer_packages/fuzzedpackages/epiphy/inst/testfiles/costTotCPP/inputs/cost.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "cost values: "<< cost << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    costTotCPP(flow,cost);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
