// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// lp_vector_cpp_DeepState_TestHarness_generation.cpp and lp_vector_cpp_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

NumericVector lp_vector_cpp(NumericVector x, double a1);

TEST(,){
  static int rinside_flag = 0;
  if(rinside_flag == 0)
  {
    rinside_flag = 1;
    RInside R;
  } std::time_t current_timestamp = std::time(0);
  std::cout << "input starts" << std::endl;
  NumericVector x  = RcppDeepState_NumericVector();
  std::string x_t = "/home/akhila/fuzzer_packages/fuzzedpackages/onlineforecast/inst/testfiles/lp_vector_cpp/libFuzzer_lp_vector_cpp/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_x.qs";
  qs::c_qsave(x,x_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "x values: "<< x << std::endl;
  NumericVector a1(1);
  a1[0]  = RcppDeepState_double();
  std::string a1_t = "/home/akhila/fuzzer_packages/fuzzedpackages/onlineforecast/inst/testfiles/lp_vector_cpp/libFuzzer_lp_vector_cpp/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_a1.qs";
  qs::c_qsave(a1,a1_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "a1 values: "<< a1 << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    lp_vector_cpp(x,a1[0]);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
