// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// KernelDist_cross_DeepState_TestHarness_generation.cpp and KernelDist_cross_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

NumericMatrix KernelDist_cross(const arma::mat& TestX, const arma::mat& X);

TEST(,){
  static int rinside_flag = 0;
  if(rinside_flag == 0)
  {
    rinside_flag = 1;
    RInside R;
  } std::time_t current_timestamp = std::time(0);
  std::cout << "input starts" << std::endl;
  std::ofstream TestX_stream;
  arma::mat TestX  = RcppDeepState_mat();
  TestX_stream.open("/home/akhila/fuzzer_packages/fuzzedpackages/orthoDr/inst/testfiles/KernelDist_cross/inputs/TestX");
  TestX_stream << TestX;
  std::cout << "TestX values: "<< TestX << std::endl;
  TestX_stream.close();
  std::ofstream X_stream;
  arma::mat X  = RcppDeepState_mat();
  X_stream.open("/home/akhila/fuzzer_packages/fuzzedpackages/orthoDr/inst/testfiles/KernelDist_cross/inputs/X");
  X_stream << X;
  std::cout << "X values: "<< X << std::endl;
  X_stream.close();
  std::cout << "input ends" << std::endl;
  try{
    KernelDist_cross(TestX,X);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
