// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// compute_pvalues_DeepState_TestHarness_generation.cpp and compute_pvalues_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

NumericVector compute_pvalues(NumericVector original_vals, NumericVector randomised_vals);

TEST(,){
  RInside R;
  std::cout << "input starts" << std::endl;
  NumericVector original_vals  = RcppDeepState_NumericVector();
  qs::c_qsave(original_vals,"/home/akhila/fuzzer_packages/fuzzedpackages/CNull/inst/testfiles/compute_pvalues/inputs/original_vals.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "original_vals values: "<< original_vals << std::endl;
  NumericVector randomised_vals  = RcppDeepState_NumericVector();
  qs::c_qsave(randomised_vals,"/home/akhila/fuzzer_packages/fuzzedpackages/CNull/inst/testfiles/compute_pvalues/inputs/randomised_vals.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "randomised_vals values: "<< randomised_vals << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    compute_pvalues(original_vals,randomised_vals);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
