// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// calcVinSph_DeepState_TestHarness_generation.cpp and calcVinSph_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

Rcpp::NumericMatrix calcVinSph(const Rcpp::NumericMatrix& latLongs, const double& r);

TEST(,){
  RInside R;
  std::cout << "input starts" << std::endl;
  NumericMatrix latLongs  = RcppDeepState_NumericMatrix();
  qs::c_qsave(latLongs,"/home/akhila/fuzzer_packages/fuzzedpackages/MGDrivE/inst/testfiles/calcVinSph/inputs/latLongs.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "latLongs values: "<< latLongs << std::endl;
  NumericVector r(1);
  r[0]  = RcppDeepState_double();
  qs::c_qsave(r,"/home/akhila/fuzzer_packages/fuzzedpackages/MGDrivE/inst/testfiles/calcVinSph/inputs/r.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "r values: "<< r << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    calcVinSph(latLongs,r[0]);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
