// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// bhnoneq_LL_DeepState_TestHarness_generation.cpp and bhnoneq_LL_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

double bhnoneq_LL(NumericVector stpar, NumericVector year, NumericVector Lbar, NumericVector ss, double Linf, double K, double Lc, int nbreaks);

TEST(,){
  RInside R;
  std::cout << "input starts" << std::endl;
  NumericVector stpar  = RcppDeepState_NumericVector();
  qs::c_qsave(stpar,"/home/akhila/fuzzer_packages/fuzzedpackages/DLMtool/inst/testfiles/bhnoneq_LL/inputs/stpar.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "stpar values: "<< stpar << std::endl;
  NumericVector year  = RcppDeepState_NumericVector();
  qs::c_qsave(year,"/home/akhila/fuzzer_packages/fuzzedpackages/DLMtool/inst/testfiles/bhnoneq_LL/inputs/year.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "year values: "<< year << std::endl;
  NumericVector Lbar  = RcppDeepState_NumericVector();
  qs::c_qsave(Lbar,"/home/akhila/fuzzer_packages/fuzzedpackages/DLMtool/inst/testfiles/bhnoneq_LL/inputs/Lbar.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "Lbar values: "<< Lbar << std::endl;
  NumericVector ss  = RcppDeepState_NumericVector();
  qs::c_qsave(ss,"/home/akhila/fuzzer_packages/fuzzedpackages/DLMtool/inst/testfiles/bhnoneq_LL/inputs/ss.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "ss values: "<< ss << std::endl;
  NumericVector Linf(1);
  Linf[0]  = RcppDeepState_double();
  qs::c_qsave(Linf,"/home/akhila/fuzzer_packages/fuzzedpackages/DLMtool/inst/testfiles/bhnoneq_LL/inputs/Linf.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "Linf values: "<< Linf << std::endl;
  NumericVector K(1);
  K[0]  = RcppDeepState_double();
  qs::c_qsave(K,"/home/akhila/fuzzer_packages/fuzzedpackages/DLMtool/inst/testfiles/bhnoneq_LL/inputs/K.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "K values: "<< K << std::endl;
  NumericVector Lc(1);
  Lc[0]  = RcppDeepState_double();
  qs::c_qsave(Lc,"/home/akhila/fuzzer_packages/fuzzedpackages/DLMtool/inst/testfiles/bhnoneq_LL/inputs/Lc.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "Lc values: "<< Lc << std::endl;
  IntegerVector nbreaks(1);
  nbreaks[0]  = RcppDeepState_int();
  qs::c_qsave(nbreaks,"/home/akhila/fuzzer_packages/fuzzedpackages/DLMtool/inst/testfiles/bhnoneq_LL/inputs/nbreaks.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "nbreaks values: "<< nbreaks << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    bhnoneq_LL(stpar,year,Lbar,ss,Linf[0],K[0],Lc[0],nbreaks[0]);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
