// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// costTotCPP_DeepState_TestHarness_generation.cpp and costTotCPP_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

Rcpp::NumericVector costTotCPP(const Rcpp::NumericMatrix& flow, const Rcpp::NumericMatrix& cost);

TEST(,){
  static int rinside_flag = 0;
  if(rinside_flag == 0)
  {
    rinside_flag = 1;
    RInside R;
  } std::time_t current_timestamp = std::time(0);
  std::cout << "input starts" << std::endl;
  NumericMatrix flow  = RcppDeepState_NumericMatrix();
  std::string flow_t = "/home/akhila/fuzzer_packages/fuzzedpackages/epiphy/inst/testfiles/costTotCPP/libFuzzer_costTotCPP/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_flow.qs";
  qs::c_qsave(flow,flow_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "flow values: "<< flow << std::endl;
  NumericMatrix cost  = RcppDeepState_NumericMatrix();
  std::string cost_t = "/home/akhila/fuzzer_packages/fuzzedpackages/epiphy/inst/testfiles/costTotCPP/libFuzzer_costTotCPP/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_cost.qs";
  qs::c_qsave(cost,cost_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "cost values: "<< cost << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    costTotCPP(flow,cost);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
