// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// fit_ab_DeepState_TestHarness_generation.cpp and fit_ab_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

Rcpp::List fit_ab(const arma::mat& xvec, const arma::mat& nvec);

TEST(,){
  RInside R;
  std::cout << "input starts" << std::endl;
  std::ofstream xvec_stream;
  arma::mat xvec  = RcppDeepState_mat();
  xvec_stream.open("/home/akhila/fuzzer_packages/fuzzedpackages/CB2/inst/testfiles/fit_ab/inputs/xvec");
  xvec_stream << xvec;
  std::cout << "xvec values: "<< xvec << std::endl;
  xvec_stream.close();
  std::ofstream nvec_stream;
  arma::mat nvec  = RcppDeepState_mat();
  nvec_stream.open("/home/akhila/fuzzer_packages/fuzzedpackages/CB2/inst/testfiles/fit_ab/inputs/nvec");
  nvec_stream << nvec;
  std::cout << "nvec values: "<< nvec << std::endl;
  nvec_stream.close();
  std::cout << "input ends" << std::endl;
  try{
    fit_ab(xvec,nvec);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
