// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// TestDoseResponseFunction_DeepState_TestHarness_generation.cpp and TestDoseResponseFunction_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

double TestDoseResponseFunction(const double& x, const double& model, const NumericVector& coef);

TEST(,){
  static int rinside_flag = 0;
  if(rinside_flag == 0)
  {
    rinside_flag = 1;
    RInside R;
  } std::time_t current_timestamp = std::time(0);
  std::cout << "input starts" << std::endl;
  NumericVector x(1);
  x[0]  = RcppDeepState_double();
  std::string x_t = "/home/akhila/fuzzer_packages/fuzzedpackages/MCPModPack/inst/testfiles/TestDoseResponseFunction/libFuzzer_TestDoseResponseFunction/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_x.qs";
  qs::c_qsave(x,x_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "x values: "<< x << std::endl;
  NumericVector model(1);
  model[0]  = RcppDeepState_double();
  std::string model_t = "/home/akhila/fuzzer_packages/fuzzedpackages/MCPModPack/inst/testfiles/TestDoseResponseFunction/libFuzzer_TestDoseResponseFunction/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_model.qs";
  qs::c_qsave(model,model_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "model values: "<< model << std::endl;
  NumericVector coef  = RcppDeepState_NumericVector();
  std::string coef_t = "/home/akhila/fuzzer_packages/fuzzedpackages/MCPModPack/inst/testfiles/TestDoseResponseFunction/libFuzzer_TestDoseResponseFunction/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_coef.qs";
  qs::c_qsave(coef,coef_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "coef values: "<< coef << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    TestDoseResponseFunction(x[0],model[0],coef);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
