// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// pairdistsubC_DeepState_TestHarness_generation.cpp and pairdistsubC_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

double pairdistsubC(const NumericVector& x_, const IntegerVector& t_, const IntegerVector& s_, const int& num_sub);

TEST(,){
  static int rinside_flag = 0;
  if(rinside_flag == 0)
  {
    rinside_flag = 1;
    RInside R;
  } std::time_t current_timestamp = std::time(0);
  std::cout << "input starts" << std::endl;
  NumericVector x_  = RcppDeepState_NumericVector();
  std::string x__t = "/home/akhila/fuzzer_packages/fuzzedpackages/MatchIt/inst/testfiles/pairdistsubC/libFuzzer_pairdistsubC/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_x_.qs";
  qs::c_qsave(x_,x__t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "x_ values: "<< x_ << std::endl;
  IntegerVector t_  = RcppDeepState_IntegerVector();
  std::string t__t = "/home/akhila/fuzzer_packages/fuzzedpackages/MatchIt/inst/testfiles/pairdistsubC/libFuzzer_pairdistsubC/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_t_.qs";
  qs::c_qsave(t_,t__t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "t_ values: "<< t_ << std::endl;
  IntegerVector s_  = RcppDeepState_IntegerVector();
  std::string s__t = "/home/akhila/fuzzer_packages/fuzzedpackages/MatchIt/inst/testfiles/pairdistsubC/libFuzzer_pairdistsubC/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_s_.qs";
  qs::c_qsave(s_,s__t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "s_ values: "<< s_ << std::endl;
  IntegerVector num_sub(1);
  num_sub[0]  = RcppDeepState_int();
  std::string num_sub_t = "/home/akhila/fuzzer_packages/fuzzedpackages/MatchIt/inst/testfiles/pairdistsubC/libFuzzer_pairdistsubC/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_num_sub.qs";
  qs::c_qsave(num_sub,num_sub_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "num_sub values: "<< num_sub << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    pairdistsubC(x_,t_,s_,num_sub[0]);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
