// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// getDelta_DeepState_TestHarness_generation.cpp and getDelta_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

arma::vec getDelta(const arma::mat& gamma, const int& m);

TEST(,){
  RInside R;
  std::cout << "input starts" << std::endl;
  std::ofstream gamma_stream;
  arma::mat gamma  = RcppDeepState_mat();
  gamma_stream.open("/home/akhila/fuzzer_packages/fuzzedpackages/MSGARCH/inst/testfiles/getDelta/inputs/gamma");
  gamma_stream << gamma;
  std::cout << "gamma values: "<< gamma << std::endl;
  gamma_stream.close();
  IntegerVector m(1);
  m[0]  = RcppDeepState_int();
  qs::c_qsave(m,"/home/akhila/fuzzer_packages/fuzzedpackages/MSGARCH/inst/testfiles/getDelta/inputs/m.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "m values: "<< m << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    getDelta(gamma,m[0]);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
