// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// rDirichlet_DeepState_TestHarness_generation.cpp and rDirichlet_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <ctime>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

NumericVector rDirichlet(const NumericVector& migrationPoint);

TEST(,){
  RInside R;
  std::time_t t = std::time(0);
  std::cout << "input starts" << std::endl;
  NumericVector migrationPoint  = RcppDeepState_NumericVector();
  std::string migrationPoint_t = "/home/akhila/fuzzer_packages/fuzzedpackages/MGDrivE/inst/testfiles/rDirichlet/AFL_rDirichlet/afl_inputs/" + std::to_string(t) + "_migrationPoint.qs";
  qs::c_qsave(migrationPoint,migrationPoint_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "migrationPoint values: "<< migrationPoint << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    rDirichlet(migrationPoint);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
