// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// DmaxVec_DeepState_TestHarness_generation.cpp and DmaxVec_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

NumericVector DmaxVec(const NumericVector& Y, const int bint);

TEST(,){
  RInside R;
  std::cout << "input starts" << std::endl;
  NumericVector Y  = RcppDeepState_NumericVector();
  qs::c_qsave(Y,"/home/akhila/fuzzer_packages/fuzzedpackages/BinSegBstrap/inst/testfiles/DmaxVec/inputs/Y.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "Y values: "<< Y << std::endl;
  IntegerVector bint(1);
  bint[0]  = RcppDeepState_int();
  qs::c_qsave(bint,"/home/akhila/fuzzer_packages/fuzzedpackages/BinSegBstrap/inst/testfiles/DmaxVec/inputs/bint.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "bint values: "<< bint << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    DmaxVec(Y,bint[0]);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
