// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// characterToInteger_DeepState_TestHarness_generation.cpp and characterToInteger_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

Rcpp::IntegerVector characterToInteger(const Rcpp::CharacterVector& x, const Rcpp::CharacterVector& levels);

TEST(,){
  RInside R;
  std::cout << "input starts" << std::endl;
  CharacterVector x  = RcppDeepState_CharacterVector();
  qs::c_qsave(x,"/home/akhila/fuzzer_packages/fuzzedpackages/MrSGUIDE/inst/testfiles/characterToInteger/inputs/x.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "x values: "<< x << std::endl;
  CharacterVector levels  = RcppDeepState_CharacterVector();
  qs::c_qsave(levels,"/home/akhila/fuzzer_packages/fuzzedpackages/MrSGUIDE/inst/testfiles/characterToInteger/inputs/levels.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "levels values: "<< levels << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    characterToInteger(x,levels);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
