// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// characterToInteger_DeepState_TestHarness_generation.cpp and characterToInteger_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

Rcpp::IntegerVector characterToInteger(const Rcpp::CharacterVector& x, const Rcpp::CharacterVector& levels);

TEST(,){
  static int rinside_flag = 0;
  if(rinside_flag == 0)
  {
    rinside_flag = 1;
    RInside R;
  } std::time_t current_timestamp = std::time(0);
  std::cout << "input starts" << std::endl;
  CharacterVector x  = RcppDeepState_CharacterVector();
  std::string x_t = "/home/akhila/fuzzer_packages/fuzzedpackages/MrSGUIDE/inst/testfiles/characterToInteger/libFuzzer_characterToInteger/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_x.qs";
  qs::c_qsave(x,x_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "x values: "<< x << std::endl;
  CharacterVector levels  = RcppDeepState_CharacterVector();
  std::string levels_t = "/home/akhila/fuzzer_packages/fuzzedpackages/MrSGUIDE/inst/testfiles/characterToInteger/libFuzzer_characterToInteger/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_levels.qs";
  qs::c_qsave(levels,levels_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "levels values: "<< levels << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    characterToInteger(x,levels);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
