// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// calcHurdleExpKernel_DeepState_TestHarness_generation.cpp and calcHurdleExpKernel_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

Rcpp::NumericMatrix calcHurdleExpKernel(const Rcpp::NumericMatrix& distMat, const double& rate, const double& p0);

TEST(,){
  RInside R;
  std::cout << "input starts" << std::endl;
  NumericMatrix distMat  = RcppDeepState_NumericMatrix();
  qs::c_qsave(distMat,"/home/akhila/fuzzer_packages/fuzzedpackages/MGDrivE/inst/testfiles/calcHurdleExpKernel/inputs/distMat.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "distMat values: "<< distMat << std::endl;
  NumericVector rate(1);
  rate[0]  = RcppDeepState_double();
  qs::c_qsave(rate,"/home/akhila/fuzzer_packages/fuzzedpackages/MGDrivE/inst/testfiles/calcHurdleExpKernel/inputs/rate.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "rate values: "<< rate << std::endl;
  NumericVector p0(1);
  p0[0]  = RcppDeepState_double();
  qs::c_qsave(p0,"/home/akhila/fuzzer_packages/fuzzedpackages/MGDrivE/inst/testfiles/calcHurdleExpKernel/inputs/p0.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "p0 values: "<< p0 << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    calcHurdleExpKernel(distMat,rate[0],p0[0]);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
