// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// ragscusum_DeepState_TestHarness_generation.cpp and ragscusum_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

NumericMatrix ragscusum(NumericMatrix& input_ra_outcomes, double limit, NumericVector& quantiles, int max_num_shuffles, int seed);

TEST(,){
  RInside R;
  std::cout << "input starts" << std::endl;
  NumericMatrix input_ra_outcomes  = RcppDeepState_NumericMatrix();
  qs::c_qsave(input_ra_outcomes,"/home/akhila/fuzzer_packages/fuzzedpackages/cusum/inst/testfiles/ragscusum/inputs/input_ra_outcomes.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "input_ra_outcomes values: "<< input_ra_outcomes << std::endl;
  NumericVector limit(1);
  limit[0]  = RcppDeepState_double();
  qs::c_qsave(limit,"/home/akhila/fuzzer_packages/fuzzedpackages/cusum/inst/testfiles/ragscusum/inputs/limit.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "limit values: "<< limit << std::endl;
  NumericVector quantiles  = RcppDeepState_NumericVector();
  qs::c_qsave(quantiles,"/home/akhila/fuzzer_packages/fuzzedpackages/cusum/inst/testfiles/ragscusum/inputs/quantiles.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "quantiles values: "<< quantiles << std::endl;
  IntegerVector max_num_shuffles(1);
  max_num_shuffles[0]  = RcppDeepState_int();
  qs::c_qsave(max_num_shuffles,"/home/akhila/fuzzer_packages/fuzzedpackages/cusum/inst/testfiles/ragscusum/inputs/max_num_shuffles.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "max_num_shuffles values: "<< max_num_shuffles << std::endl;
  IntegerVector seed(1);
  seed[0]  = RcppDeepState_int();
  qs::c_qsave(seed,"/home/akhila/fuzzer_packages/fuzzedpackages/cusum/inst/testfiles/ragscusum/inputs/seed.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "seed values: "<< seed << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    ragscusum(input_ra_outcomes,limit[0],quantiles,max_num_shuffles[0],seed[0]);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
