// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// lp_vector_cpp_DeepState_TestHarness_generation.cpp and lp_vector_cpp_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

NumericVector lp_vector_cpp(NumericVector x, double a1);

TEST(,){
  RInside R;
  std::cout << "input starts" << std::endl;
  NumericVector x  = RcppDeepState_NumericVector();
  qs::c_qsave(x,"/home/akhila/fuzzer_packages/fuzzedpackages/onlineforecast/inst/testfiles/lp_vector_cpp/inputs/x.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "x values: "<< x << std::endl;
  NumericVector a1(1);
  a1[0]  = RcppDeepState_double();
  qs::c_qsave(a1,"/home/akhila/fuzzer_packages/fuzzedpackages/onlineforecast/inst/testfiles/lp_vector_cpp/inputs/a1.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "a1 values: "<< a1 << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    lp_vector_cpp(x,a1[0]);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
