// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// DmaxVec_DeepState_TestHarness_generation.cpp and DmaxVec_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <ctime>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

NumericVector DmaxVec(const NumericVector& Y, const int bint);

TEST(,){
  RInside R;
  std::time_t t = std::time(0);
  std::cout << "input starts" << std::endl;
  NumericVector Y  = RcppDeepState_NumericVector();
  std::string Y_t = "/home/akhila/fuzzer_packages/fuzzedpackages/BinSegBstrap/inst/testfiles/DmaxVec/AFL_DmaxVec/afl_inputs/" + std::to_string(t) + "_Y.qs";
  qs::c_qsave(Y,Y_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "Y values: "<< Y << std::endl;
  IntegerVector bint(1);
  bint[0]  = RcppDeepState_int();
  std::string bint_t = "/home/akhila/fuzzer_packages/fuzzedpackages/BinSegBstrap/inst/testfiles/DmaxVec/AFL_DmaxVec/afl_inputs/" + std::to_string(t) + "_bint.qs";
  qs::c_qsave(bint,bint_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "bint values: "<< bint << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    DmaxVec(Y,bint[0]);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
