// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// MCPModFitDRModels_DeepState_TestHarness_generation.cpp and MCPModFitDRModels_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

List MCPModFitDRModels(const int& endpoint_index_arg, const IntegerVector& selected_models_arg, const NumericVector& x_arg, const NumericVector& y_arg, const double& delta_arg, const double& direction_index_arg, const int& maxit_arg, const NumericVector& theta_vector_arg);

TEST(,){
  RInside R;
  std::cout << "input starts" << std::endl;
  IntegerVector endpoint_index_arg(1);
  endpoint_index_arg[0]  = RcppDeepState_int();
  qs::c_qsave(endpoint_index_arg,"/home/akhila/fuzzer_packages/fuzzedpackages/MCPModPack/inst/testfiles/MCPModFitDRModels/inputs/endpoint_index_arg.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "endpoint_index_arg values: "<< endpoint_index_arg << std::endl;
  IntegerVector selected_models_arg  = RcppDeepState_IntegerVector();
  qs::c_qsave(selected_models_arg,"/home/akhila/fuzzer_packages/fuzzedpackages/MCPModPack/inst/testfiles/MCPModFitDRModels/inputs/selected_models_arg.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "selected_models_arg values: "<< selected_models_arg << std::endl;
  NumericVector x_arg  = RcppDeepState_NumericVector();
  qs::c_qsave(x_arg,"/home/akhila/fuzzer_packages/fuzzedpackages/MCPModPack/inst/testfiles/MCPModFitDRModels/inputs/x_arg.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "x_arg values: "<< x_arg << std::endl;
  NumericVector y_arg  = RcppDeepState_NumericVector();
  qs::c_qsave(y_arg,"/home/akhila/fuzzer_packages/fuzzedpackages/MCPModPack/inst/testfiles/MCPModFitDRModels/inputs/y_arg.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "y_arg values: "<< y_arg << std::endl;
  NumericVector delta_arg(1);
  delta_arg[0]  = RcppDeepState_double();
  qs::c_qsave(delta_arg,"/home/akhila/fuzzer_packages/fuzzedpackages/MCPModPack/inst/testfiles/MCPModFitDRModels/inputs/delta_arg.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "delta_arg values: "<< delta_arg << std::endl;
  NumericVector direction_index_arg(1);
  direction_index_arg[0]  = RcppDeepState_double();
  qs::c_qsave(direction_index_arg,"/home/akhila/fuzzer_packages/fuzzedpackages/MCPModPack/inst/testfiles/MCPModFitDRModels/inputs/direction_index_arg.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "direction_index_arg values: "<< direction_index_arg << std::endl;
  IntegerVector maxit_arg(1);
  maxit_arg[0]  = RcppDeepState_int();
  qs::c_qsave(maxit_arg,"/home/akhila/fuzzer_packages/fuzzedpackages/MCPModPack/inst/testfiles/MCPModFitDRModels/inputs/maxit_arg.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "maxit_arg values: "<< maxit_arg << std::endl;
  NumericVector theta_vector_arg  = RcppDeepState_NumericVector();
  qs::c_qsave(theta_vector_arg,"/home/akhila/fuzzer_packages/fuzzedpackages/MCPModPack/inst/testfiles/MCPModFitDRModels/inputs/theta_vector_arg.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "theta_vector_arg values: "<< theta_vector_arg << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    MCPModFitDRModels(endpoint_index_arg[0],selected_models_arg,x_arg,y_arg,delta_arg[0],direction_index_arg[0],maxit_arg[0],theta_vector_arg);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
