// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// calcGammaKernel_DeepState_TestHarness_generation.cpp and calcGammaKernel_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

Rcpp::NumericMatrix calcGammaKernel(const Rcpp::NumericMatrix& distMat, const double& shape, const double& rate);

TEST(,){
  static int rinside_flag = 0;
  if(rinside_flag == 0)
  {
    rinside_flag = 1;
    RInside R;
  } std::time_t current_timestamp = std::time(0);
  std::cout << "input starts" << std::endl;
  NumericMatrix distMat  = RcppDeepState_NumericMatrix();
  std::string distMat_t = "/home/akhila/fuzzer_packages/fuzzedpackages/MGDrivE/inst/testfiles/calcGammaKernel/libFuzzer_calcGammaKernel/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_distMat.qs";
  qs::c_qsave(distMat,distMat_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "distMat values: "<< distMat << std::endl;
  NumericVector shape(1);
  shape[0]  = RcppDeepState_double();
  std::string shape_t = "/home/akhila/fuzzer_packages/fuzzedpackages/MGDrivE/inst/testfiles/calcGammaKernel/libFuzzer_calcGammaKernel/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_shape.qs";
  qs::c_qsave(shape,shape_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "shape values: "<< shape << std::endl;
  NumericVector rate(1);
  rate[0]  = RcppDeepState_double();
  std::string rate_t = "/home/akhila/fuzzer_packages/fuzzedpackages/MGDrivE/inst/testfiles/calcGammaKernel/libFuzzer_calcGammaKernel/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_rate.qs";
  qs::c_qsave(rate,rate_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "rate values: "<< rate << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    calcGammaKernel(distMat,shape[0],rate[0]);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
