// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// TestDoseResponseFunction_DeepState_TestHarness_generation.cpp and TestDoseResponseFunction_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

double TestDoseResponseFunction(const double& x, const double& model, const NumericVector& coef);

TEST(,){
  RInside R;
  std::cout << "input starts" << std::endl;
  NumericVector x(1);
  x[0]  = RcppDeepState_double();
  qs::c_qsave(x,"/home/akhila/fuzzer_packages/fuzzedpackages/MCPModPack/inst/testfiles/TestDoseResponseFunction/inputs/x.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "x values: "<< x << std::endl;
  NumericVector model(1);
  model[0]  = RcppDeepState_double();
  qs::c_qsave(model,"/home/akhila/fuzzer_packages/fuzzedpackages/MCPModPack/inst/testfiles/TestDoseResponseFunction/inputs/model.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "model values: "<< model << std::endl;
  NumericVector coef  = RcppDeepState_NumericVector();
  qs::c_qsave(coef,"/home/akhila/fuzzer_packages/fuzzedpackages/MCPModPack/inst/testfiles/TestDoseResponseFunction/inputs/coef.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "coef values: "<< coef << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    TestDoseResponseFunction(x[0],model[0],coef);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
