// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// pairdistsubC_DeepState_TestHarness_generation.cpp and pairdistsubC_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

double pairdistsubC(const NumericVector& x_, const IntegerVector& t_, const IntegerVector& s_, const int& num_sub);

TEST(,){
  RInside R;
  std::cout << "input starts" << std::endl;
  NumericVector x_  = RcppDeepState_NumericVector();
  qs::c_qsave(x_,"/home/akhila/fuzzer_packages/fuzzedpackages/MatchIt/inst/testfiles/pairdistsubC/inputs/x_.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "x_ values: "<< x_ << std::endl;
  IntegerVector t_  = RcppDeepState_IntegerVector();
  qs::c_qsave(t_,"/home/akhila/fuzzer_packages/fuzzedpackages/MatchIt/inst/testfiles/pairdistsubC/inputs/t_.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "t_ values: "<< t_ << std::endl;
  IntegerVector s_  = RcppDeepState_IntegerVector();
  qs::c_qsave(s_,"/home/akhila/fuzzer_packages/fuzzedpackages/MatchIt/inst/testfiles/pairdistsubC/inputs/s_.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "s_ values: "<< s_ << std::endl;
  IntegerVector num_sub(1);
  num_sub[0]  = RcppDeepState_int();
  qs::c_qsave(num_sub,"/home/akhila/fuzzer_packages/fuzzedpackages/MatchIt/inst/testfiles/pairdistsubC/inputs/num_sub.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "num_sub values: "<< num_sub << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    pairdistsubC(x_,t_,s_,num_sub[0]);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
